# .github/workflows/terraform-deploy.yml
name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      resource_type:
        description: 'Type of resource to deploy'
        required: true
        type: choice
        options:
          - ec2_instance
          - s3_bucket
      
      name:
        description: 'Resource name'
        required: true
        type: string
      
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      
      region:
        description: 'AWS region'
        required: true
        default: 'eu-west-2'
        type: choice
        options:
          - eu-west-2
          - us-east-1
          - us-west-2
          - eu-west-1
      
      # EC2 specific inputs
      instance_type:
        description: 'EC2 instance type (for EC2 only)'
        required: false
        default: 't2.micro'
        type: string
      
      volume_size:
        description: 'Root volume size in GB (for EC2 only)'
        required: false
        default: '20'
        type: string
      
      assign_eip:
        description: 'Assign Elastic IP to EC2 instance'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      
      # Existing VPC inputs for EC2
      subnet_id:
        description: 'Subnet for EC2 instance'
        required: false
        default: 'subnet-07759e500cfdfb6b2'
        type: choice
        options:
          - 'subnet-07759e500cfdfb6b2' # eu-west-2a
          - 'subnet-0d95a35be6e1fb603' # eu-west-2b
          - 'subnet-00e88d7e1a6b7c689' # eu-west-2c
      
      # S3 specific inputs
      bucket_name:
        description: 'S3 bucket name (for S3 only)'
        required: false
        type: string
      
      versioning_enabled:
        description: 'Enable versioning for S3 bucket'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

env:
    APP_WEBHOOK_URL: https://platform-hub.onrender.com/api/webhook/deployment
    SECURITY_GROUP_ID: "sg-060323606252babd1"

jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    
    # Configure AWS credentials with role assumption
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::436549840164:role/github_action_role
        aws-region: ${{ github.event.inputs.region }}
    
    - name: Generate Deployment ID
      id: deployment_id
      run: echo "id=deploy-$(date +%s)" >> $GITHUB_OUTPUT
    
    - name: Generate Terraform Configuration
      run: |
        mkdir -p terraform-config
        
        # Create variables.tf to declare all variables
        cat > terraform-config/variables.tf << EOF
        variable "deployment_id" {
          description = "Unique identifier for this deployment"
          type        = string
        }
        
        # Common variables
        variable "region" {
          description = "AWS region for the resources"
          type        = string
          default     = "${{ github.event.inputs.region }}"
        }
        
        variable "environment" {
          description = "Deployment environment (dev, staging, prod)"
          type        = string
          default     = "${{ github.event.inputs.environment }}"
        }
        
        variable "name" {
          description = "Resource name"
          type        = string
          default     = "${{ github.event.inputs.name }}"
        }
        
        # EC2 specific variables
        variable "instance_type" {
          description = "EC2 instance type"
          type        = string
          default     = "${{ github.event.inputs.instance_type }}"
        }
        
        variable "subnet_id" {
          description = "Subnet ID for the EC2 instance"
          type        = string
          default     = "${{ github.event.inputs.subnet_id }}"
        }
        
        variable "root_volume_size" {
          description = "Size in GB for the root volume"
          type        = number
          default     = ${{ github.event.inputs.volume_size }}
        }
        
        variable "assign_eip" {
          description = "Whether to assign Elastic IP to the instance"
          type        = bool
          default     = ${{ github.event.inputs.assign_eip }}
        }
        
        variable "security_group_ids" {
          description = "List of security group IDs"
          type        = list(string)
          default     = ["${{ env.SECURITY_GROUP_ID }}"]
        }
        
        # S3 specific variables
        variable "bucket_name" {
          description = "Name of the S3 bucket"
          type        = string
          default     = "${{ github.event.inputs.bucket_name }}"
        }
        
        variable "versioning_enabled" {
          description = "Whether to enable bucket versioning"
          type        = bool
          default     = ${{ github.event.inputs.versioning_enabled || 'false' }}
        }
        EOF
        
        # Create resource-specific main.tf
        if [[ "${{ github.event.inputs.resource_type }}" == "ec2_instance" ]]; then
          cat > terraform-config/main.tf << EOF
        provider "aws" {
          region = var.region
        }
        
        module "ec2_instance" {
          source = "../terraform/modules/ec2_instance"
          
          name                = var.name
          environment         = var.environment
          region              = var.region
          instance_type       = var.instance_type
          subnet_id           = var.subnet_id
          security_group_ids  = var.security_group_ids
          root_volume_size    = var.root_volume_size
          assign_eip          = var.assign_eip
          deployment_id       = var.deployment_id
        }
        EOF
          
          # Create outputs.tf for EC2
          cat > terraform-config/outputs.tf << EOF
        output "instance_id" {
          value = module.ec2_instance.instance_id
          description = "The ID of the created EC2 instance"
        }
        
        output "public_ip" {
          value = module.ec2_instance.elastic_ip != null ? module.ec2_instance.elastic_ip : module.ec2_instance.instance_public_ip
          description = "The public IP address of the instance"
        }
        
        output "ssh_command" {
          value = module.ec2_instance.ssh_command
          description = "SSH command to connect to the instance"
        }
        EOF
          
        elif [[ "${{ github.event.inputs.resource_type }}" == "s3_bucket" ]]; then
          cat > terraform-config/main.tf << EOF
        provider "aws" {
          region = var.region
        }
        
        module "s3_bucket" {
          source = "../terraform/modules/s3_bucket"
          
          bucket_name        = var.bucket_name
          environment        = var.environment
          region             = var.region
          versioning_enabled = var.versioning_enabled
          deployment_id      = var.deployment_id
        }
        EOF
          
          # Create outputs.tf for S3
          cat > terraform-config/outputs.tf << EOF
        output "bucket_id" {
          value = module.s3_bucket.bucket_id
          description = "The name of the bucket"
        }
        
        output "bucket_arn" {
          value = module.s3_bucket.bucket_arn
          description = "The ARN of the bucket"
        }
        
        output "bucket_domain_name" {
          value = module.s3_bucket.bucket_domain_name
          description = "The domain name of the bucket"
        }
        EOF
        
        else
          echo "Unsupported resource type: ${{ github.event.inputs.resource_type }}"
          exit 1
        fi
        
        # Copy modules directory to workspace
        mkdir -p terraform-config/modules
        cp -r terraform/modules/* terraform-config/modules/
    
    - name: Terraform Init
      working-directory: terraform-config
      run: terraform init
    
    - name: Terraform Plan
      working-directory: terraform-config
      run: terraform plan -var="deployment_id=${{ steps.deployment_id.outputs.id }}" -out=tfplan
      
    - name: Terraform Apply
      working-directory: terraform-config
      run: terraform apply -auto-approve tfplan
    
    - name: Capture Terraform Outputs
      working-directory: terraform-config
      id: terraform_output
      run: |
        OUTPUTS=$(terraform output -json)
        echo "outputs=$OUTPUTS" >> $GITHUB_OUTPUT
    
    - name: Post Success Results to Application
      if: success() && env.APP_WEBHOOK_URL != ''
      run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "secret": "${{ secrets.WEBHOOK_SECRET }}",
            "deployment_id": "${{ steps.deployment_id.outputs.id }}",
            "status": "completed",
            "resource_type": "${{ github.event.inputs.resource_type }}",
            "name": "${{ github.event.inputs.name }}",
            "environment": "${{ github.event.inputs.environment }}",
            "region": "${{ github.event.inputs.region }}",
            "outputs": ${{ steps.terraform_output.outputs.outputs }},
            "requested_by": "${{ github.actor }}",
            "completed_at": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
          }' ${{ env.APP_WEBHOOK_URL }}
      
    - name: Post Failure Results to Application
      if: failure() && env.APP_WEBHOOK_URL != ''
      run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "secret": "${{ secrets.WEBHOOK_SECRET }}",
            "deployment_id": "${{ steps.deployment_id.outputs.id }}",
            "status": "failed",
            "resource_type": "${{ github.event.inputs.resource_type }}",
            "name": "${{ github.event.inputs.name }}",
            "environment": "${{ github.event.inputs.environment }}",
            "region": "${{ github.event.inputs.region }}",
            "outputs": {},
            "error_message": "Deployment failed in GitHub Actions workflow",
            "requested_by": "${{ github.actor }}",
            "completed_at": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
          }' ${{ env.APP_WEBHOOK_URL }}